'use client'

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  mounted: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    'nav.services': 'Services',
    'nav.problems': 'Problems We Solve',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.portfolio': 'Portfolio',
    'nav.contact': 'Contact',
    'hero.title': 'We build websites that bring you customers.',
    'hero.promise': 'Bilingual sites for businesses in Charleston and Spain. Built to get you found, get you calls, and get you growing.',
    'hero.subtitle': 'We handle the tech. You run your business.',
    'hero.cta': 'Get Started',
    'hero.learn': 'Learn More',
    'about.title': 'About Us',
    'about.subtitle': 'Your local web development team',
    'about.description': 'We started IberiaTech in 2024 because too many small businesses were paying too much for websites that did not work. We keep it simple: a good site, fair price, and someone who picks up the phone.',
    'about.mission': 'What We Do',
    'about.mission.text': 'We build websites for small and medium businesses in Charleston and Spain. Sites that actually bring in customers, not just look pretty.',
    'about.expertise': 'How We Work',
    'about.expertise.text': 'You tell us what your business needs. We build it, launch it, and make sure it works. No jargon, no runaround.',
    'services.title': 'What We Offer',
    'services.subtitle': 'Websites for small and medium businesses. Clear pricing, no surprises.',
    'services.webdev.title': 'Web Development',
    'services.webdev.desc': 'Clean, fast websites that work on every screen. No templates, no page builders.',
    'services.mobile.title': 'Mobile-First Design',
    'services.mobile.desc': 'Most of your visitors are on their phone. Your site will look great there first.',
    'services.bilingual.title': 'Bilingual Websites',
    'services.bilingual.desc': 'English and Spanish built in from day one. Not a plugin, not a translation tool.',
    'services.security.title': 'Security & Authentication',
    'services.security.desc': 'SSL, secure forms, proper hosting. Your data and your customers stay safe.',
    'services.performance.title': 'SEO & Speed',
    'services.performance.desc': 'Fast loading, clean code, and set up so Google can actually find you.',
    'services.support.title': 'Ongoing Support',
    'services.ai.title': 'Smart Features',
    'services.support.desc': 'We do not disappear after launch. Updates, fixes, questions. We are here.',
    'pricing.title': 'Clear Pricing, No Surprises',
    'pricing.anchor': 'Sites start at $1,000. Check the ranges below to see if we fit your budget.',
    'pricing.subtitle': 'One-time pricing. You pay, we build, you own it. No subscriptions, no hidden fees.',
    'pricing.subtitle.charleston': 'Fair rates for Charleston, SC and beyond.',
    'pricing.value': 'Good work at honest prices. You will know exactly what you are paying for.',
    'pricing.starter.name': 'Starter',
    'pricing.starter.price': '$1,000 – $1,800',
    'pricing.starter.desc': '',
    'pricing.business.name': 'Business',
    'pricing.business.price': '$2,000 – $4,000',
    'pricing.business.desc': '',
    'pricing.custom.name': 'Custom',
    'pricing.custom.price': '$4,000+',
    'pricing.custom.desc': '',
    'pricing.popular': 'Most Popular',
    'pricing.getstarted': 'Get Started',
    'pricing.cta.starter': 'Launch My Website',
    'pricing.cta.business': 'Grow My Business',
    'pricing.cta.custom': 'Get a Quote',
    'pricing.custom': 'Ready to get started? Let\'s talk about your project →',
    'pricing.consultation': 'All packages include free consultation and project planning',
    'problems.title': 'Sound familiar?',
    'problems.subtitle': 'A lot of businesses in Charleston and Spain still depend on word of mouth alone. That works until it does not.',
    'problems.without.title': 'Without a good website:',
    'problems.with.title': 'With us, you get:',
    'problems.cta.title': 'Ready to fix this?',
    'problems.cta.subtitle': '',
    'problems.cta.button': 'Get Started Today',
    'portfolio.title': 'Our Work',
    'portfolio.subtitle': 'Real sites we have built for real businesses',
    'contact.title': 'Let us talk about your project',
    'contact.subtitle': 'Tell us what you need. We will get back to you within 24 hours.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.company': 'Company',
    'contact.message': 'Message',
    'contact.send': 'Send Message',
    'contact.phone': 'Phone',
    'contact.location': 'Location',
    'footer.company': 'IberiaTech Solutions',
    'footer.description': 'Bilingual websites for small and medium businesses in Charleston and Spain.',
    'footer.services': 'Services',
    'footer.services.webdev': 'Custom Web Development',
    'footer.services.react': 'Modern Web Design',
    'footer.services.supabase': 'Secure Data Management',
    'footer.services.bilingual': 'Bilingual Websites',
    'footer.services.translation': 'Website Translation',
    'footer.services.seo': 'SEO Optimization',
    'footer.services.mobile': 'Mobile-Friendly Design',
    'hero.subtitle2': 'In English, Spanish, or both',
    'hero.tagline': 'Modern, bilingual websites that actually work.',
    'hero.features.ai': 'AI-Powered',
    'hero.features.mobile': 'Mobile-First',
    'hero.features.bilingual': 'Bilingual',
    'hero.cta.start': 'Start Your Project',
    'hero.cta.contact': 'Get in Touch',
    'cta.strategy.title': 'Book a Free Strategy Call',
    'cta.strategy.subtitle': '30 minutes. No pressure. We\'ll map out the best path for your business.',
    'cta.strategy.button': 'Book My Call',
    'cta.demo.title': 'See a Demo Website Sample',
    'cta.demo.subtitle': 'View a real project we built: mobile-friendly, fast, bilingual.',
    'cta.demo.button': 'See the Demo',
    'cta.quote24.title': 'Get Your Project Quote in 24 Hours',
    'cta.quote24.subtitle': 'Tell us about your project. We\'ll respond with a clear quote and next steps.',
    'cta.quote24.button': 'Get My Quote',
    'about.title2': 'About Us',
    'about.description2': 'We started IberiaTech in 2024 to help small businesses get online without the headache. We work with construction companies, law offices, restaurants, and local shops in Charleston and Spain. We speak both languages, we understand both markets, and we build sites that actually bring in business.',
    'about.stats.portfolio': 'Growing Portfolio',
    'about.stats.countries': 'Countries Served',
    'about.stats.satisfaction': 'Client Satisfaction',
    'about.founder.title': 'Founder & Lead Developer',
    'about.founder.story.title': 'The person behind IberiaTech',
    'about.founder.story.text': 'I have been building websites for over 5 years. I grew up in Spain and live in Charleston, so I understand both markets firsthand. I started IberiaTech because I saw too many small businesses paying too much for sites that did not do anything for them. When you work with us, you work with me directly.',
    'about.founder.experience.us': '5+ years US market experience',
    'about.founder.experience.spain': 'Native Spanish speaker & culture expert',
    'about.testimonials.title': 'Testimonios de Clientes',
    'about.testimonials.quote': 'Luis at IberiaTech does amazing work. He is a skilled developer and really great to work with.',
    'about.testimonials.author': 'Dave Ingram',
    'about.testimonials.company': 'Querri',
    'services.title2': 'What We Build',
    'services.subtitle2': 'Websites for businesses in Charleston, Spain, and beyond. Built to get you customers.',
    'services.subtitle3': 'Sites and apps that bring in leads and pay for themselves.',
    'services.page.title': 'Our services',
    'services.page.subtitle': 'Websites, SEO, bilingual sites, analytics, and ongoing support. You will know exactly what you get and when.',
    'portfolio.title2': 'About Luis Lozoya',
    'portfolio.subtitle2': 'Founder of IberiaTech Solutions',
    'portfolio.subtitle3': 'I help small and medium companies in Charleston and Spain grow online with modern, bilingual websites',
    'portfolio.project.title': 'Featured Project: Cursor Rules Hub',
    'portfolio.coming.title': 'My Experience',
    'portfolio.cta.title': 'Ready to Start Your Project?',
    'portfolio.cta.start': 'Start Your Project',
    'portfolio.cta.contact': 'Get in Touch',
    'contact.title2': 'Tell Us About Your Project',
    'contact.subtitle2': 'Send us a message. We will get back to you within 24 hours.',
    'contact.form.name': 'Your full name',
    'contact.form.company': 'Your company name',
    'contact.form.message': 'Tell me about your project...',
    'contact.form.sending': 'Sending...',
    'why.title': 'Why Choose IberiaTech Solutions?',
    'why.subtitle': 'We\'re more than a web development agency - we\'re your strategic technology partner with bilingual expertise, AI solutions, and long-term support.',
    'why.bilingual.title': 'Complete Bilingual Expertise',
    'why.bilingual.desc': 'Deep understanding of US and Spanish markets, ensuring your site speaks both languages naturally.',
    'why.tech.title': 'Modern Technology Stack',
    'why.tech.desc': 'We use modern technologies to create fast, secure websites that grow with your business.',
    'why.ai.title': 'AI-Enabled Solutions',
    'why.ai.desc': 'We automate workflows and improve user experience with artificial intelligence and smart chatbots.',
    'why.personal.title': 'Direct Personal Approach',
    'why.personal.desc': 'Direct communication with the founder - no middlemen or large teams, just personalized attention.',
    'why.support.title': 'Long-term Support',
    'why.support.desc': 'Lasting relationships with continuous support, proactive maintenance, and comprehensive care plans.',
    'trusted.title': 'Trusted by',
    'trusted.coming': 'More clients coming soon...',
    'visual.sites.title': 'Recent work',
    'visual.sites.subtitle': 'Real sites, real businesses. Click to see them live.',
    'portfolio.disclaimer': 'Note: Projects shown include both IberiaTech Solutions\' independent clients and professional work Luis Lozoya completed as a contractor for partner agencies.',
    'pricing.month': 'project',
    'pricing.cta': 'Get Started',
    'pricing.compare.title': 'Compare plans',
    'pricing.compare.why': 'Why this price? Compare apples to apples.',
    'pricing.compare.whySub': 'See what you get at each level.',
    'pricing.compare.pages': 'Pages',
    'pricing.compare.seo': 'SEO',
    'pricing.compare.analytics': 'Analytics',
    'pricing.compare.delivery': 'Delivery',
    'pricing.compare.revisions': 'Revisions',
    'pricing.compare.support': 'Post-launch support',
    'pricing.compare.bilingual': 'English + Spanish',
    'pricing.compare.starter.pages': 'Up to 4 (e.g. Home, About, Services, Contact)',
    'pricing.compare.starter.seo': 'Basic (meta, sitemap)',
    'pricing.compare.starter.analytics': 'No',
    'pricing.compare.starter.delivery': '1 week',
    'pricing.compare.starter.revisions': '2 rounds',
    'pricing.compare.starter.support': '1 month',
    'pricing.compare.starter.bilingual': 'Included',
    'pricing.compare.business.pages': 'Up to 7 (e.g. Home, About, Services, Portfolio, Testimonials, FAQ, Contact)',
    'pricing.compare.business.seo': 'Advanced + Google Analytics',
    'pricing.compare.business.analytics': 'Included',
    'pricing.compare.business.delivery': '2–4 weeks',
    'pricing.compare.business.revisions': '3 rounds',
    'pricing.compare.business.support': '3 months',
    'pricing.compare.business.bilingual': 'Included (cultural adaptation)',
    'pricing.compare.custom': 'Tailored',
    'pricing.compare.feature': 'What you get',
    'pricing.compare.custom.pages': 'Custom (eCommerce, booking, member portals, forms)',
    'pricing.compare.custom.seo': 'Full SEO + Analytics',
    'pricing.compare.custom.analytics': 'Included',
    'pricing.compare.custom.delivery': '5–7 weeks',
    'pricing.compare.custom.revisions': 'Included',
    'pricing.compare.custom.support': '6 months',
    'pricing.compare.custom.bilingual': 'Included',
    'pricing.maintenance.title': 'Optional monthly support',
    'pricing.maintenance.subtitle': 'Peace of mind without break-fix surprises. Recurring plans for updates, backups, and improvements.',
    'pricing.maintenance.basic.name': 'Basic Support',
    'pricing.maintenance.basic.price': '$49/mo',
    'pricing.maintenance.basic.desc': 'Updates and backups. Keep your site secure and up to date.',
    'pricing.maintenance.growth.name': 'Growth Support',
    'pricing.maintenance.growth.price': '$99/mo',
    'pricing.maintenance.growth.desc': 'Basic + analytics review and SEO tweaks. Good for growing traffic.',
    'pricing.maintenance.premium.name': 'Premium Support',
    'pricing.maintenance.premium.price': '$199/mo',
    'pricing.maintenance.premium.desc': 'Full maintenance and improvements. Content updates, priority support, and ongoing optimization.',
    'pricing.addons.title': 'Optional add-ons',
    'pricing.addons.subtitle': 'Add to any package. One-time price, no surprises.',
    'pricing.addons.chatbot.name': 'Chatbot Integration',
    'pricing.addons.chatbot.price': '$199',
    'pricing.addons.chatbot.desc': 'AI-powered chat on your site. Answers visitors 24/7.',
    'pricing.addons.seo.name': 'Advanced SEO Package',
    'pricing.addons.seo.price': '$299',
    'pricing.addons.seo.desc': 'Deeper optimization, local SEO, structured data.',
    'pricing.addons.analytics.name': 'Premium Analytics Setup',
    'pricing.addons.analytics.price': '$249',
    'pricing.addons.analytics.desc': 'Google Analytics 4, goals, and conversion tracking.',
    'pricing.payment.title': 'Payment options',
    'pricing.payment.subtitle': 'Flexible ways to pay. No surprises.',
    'pricing.payment.option1': '50% to start, 50% on launch (all build packages)',
    'pricing.payment.option2': 'Payment plans in 2–3 stages available on request',
    'services.detail.title': 'What\'s included',
    'services.detail.seo.title': 'SEO deliverables',
    'services.detail.seo.desc': 'What we actually include so you show up on Google:',
    'services.detail.seo.1': 'Meta titles & descriptions (every page)',
    'services.detail.seo.2': 'Sitemap + mobile-friendly structure',
    'services.detail.seo.3': 'Basic schema (Business+: structured data)',
    'services.detail.seo.4': 'Fast load times & clean URLs',
    'services.detail.ai.title': 'What "AI powered" means',
    'services.detail.ai.desc': 'We use AI to help your site work harder: optional chatbot that answers visitor questions, smart contact forms, and content suggestions. No extra cost on Business and Premium.',
    'services.detail.timeline.title': 'Build timeline',
    'services.detail.timeline.desc': 'Starter: 1 week. Business: 2–4 weeks. Premium / eCommerce: 5–7 weeks. We’ll confirm your dates before we start.',
    'services.detail.hosting.title': 'Domain + hosting',
    'services.detail.hosting.desc': 'We can guide you step-by-step (you keep full control) or handle setup for you. Hosting is not included in the build price; we’ll recommend affordable options.',
    'faq.title': 'Frequently asked questions',
    'faq.subtitle': 'Common questions before you get started.',
    'faq.q1': 'How long does the build take?',
    'faq.a1': 'Starter sites: 1 week. Business (5–7 pages): 2–4 weeks. Premium / eCommerce: 5–7 weeks. We agree on a timeline before starting.',
    'faq.q2': 'What support do I get after launch?',
    'faq.a2': 'Starter includes 1 month of post-launch support; Business includes 3 months; Premium includes 6 months. After that, you can add a monthly Care or Growth plan.',
    'faq.q3': 'How many revisions are included?',
    'faq.a3': 'Starter: 2 rounds of revisions. Business: 3 rounds. Premium: revisions included as needed within scope. We’ll confirm the exact number in your quote.',
    'faq.q4': 'Do you handle hosting and domain?',
    'faq.a4': 'We can set up domain and hosting for you or guide you through it. Hosting is not included in the build price; we recommend affordable providers and help with setup.',
    'faq.q5': 'Do I need to buy a domain myself?',
    'faq.a5': 'You can buy your own domain (we’ll tell you where and how) or we can handle purchase and connection. Either way, the domain stays in your name.',
    'faq.q6': 'What about ongoing maintenance?',
    'faq.a6': 'We offer monthly Care (updates, backups, monitoring) and Growth (Care + content and SEO tweaks) plans. Perfect if you want ongoing help without hiring in-house.',
    'results.title': 'Real results',
    'results.metric': 'Our clients see up to 30% more leads in the first 90 days.',
    'results.subtitle': 'We care about what happens after your site goes live.',
    'guarantee.title': 'Your peace of mind',
    'guarantee.moneyback': 'Money-back if you\'re not satisfied before launch',
    'guarantee.satisfaction': 'Satisfaction guarantee. We fix it until you\'re happy.',
    'guarantee.timeline': 'Delivery timeline pledge. We stick to agreed dates.',
  },
  es: {
    'nav.services': 'Servicios',
    'nav.problems': 'Problemas que Resolvemos',
    'nav.pricing': 'Precios',
    'nav.faq': 'FAQ',
    'nav.portfolio': 'Portafolio',
    'nav.contact': 'Contacto',
    'hero.title': 'Construimos sitios web que te traen clientes.',
    'hero.promise': 'Sitios bilingues para negocios en Charleston y España. Hechos para que te encuentren, te llamen y crezcas.',
    'hero.subtitle': 'Nosotros nos encargamos de la tecnología. Tu enfocate en tu negocio.',
    'hero.subtitle2': 'En inglés, español, o ambos',
    'hero.tagline': 'Sitios web modernos y bilingues que realmente funcionan.',
    'hero.features.ai': 'Con IA',
    'hero.features.mobile': 'Mobile-First',
    'hero.features.bilingual': 'Bilingüe',
    'hero.cta.start': 'Comienza Tu Proyecto',
    'hero.cta.contact': 'Ponte en Contacto',
    'cta.strategy.title': 'Reserva una llamada de estrategia gratis',
    'cta.strategy.subtitle': '30 minutos. Sin compromiso. Definimos la mejor ruta para tu negocio.',
    'cta.strategy.button': 'Reservar mi llamada',
    'cta.demo.title': 'Ver una muestra de sitio web',
    'cta.demo.subtitle': 'Mira un proyecto real que construimos: móvil, rápido, bilingüe.',
    'cta.demo.button': 'Ver la demo',
    'cta.quote24.title': 'Recibe tu cotización en 24 horas',
    'cta.quote24.subtitle': 'Cuéntanos tu proyecto. Te respondemos con una cotización clara y próximos pasos.',
    'cta.quote24.button': 'Obtener mi cotización',
    'hero.cta': 'Comenzar',
    'hero.learn': 'Saber Más',
    'about.title': 'Sobre nosotros',
    'about.subtitle': 'Tu equipo local de desarrollo web',
    'about.description': 'Empezamos IberiaTech en 2024 porque demasiados negocios estaban pagando de mas por sitios web que no servian. Lo hacemos simple: un buen sitio, precio justo, y alguien que contesta el telefono.',
    'about.description2': 'Empezamos IberiaTech en 2024 para ayudar a negocios a estar online sin complicaciones. Trabajamos con empresas de construccion, bufetes, restaurantes y tiendas locales en Charleston y España. Hablamos los dos idiomas, entendemos los dos mercados, y construimos sitios que realmente traen negocio.',
    'about.stats.portfolio': 'Portafolio en Crecimiento',
    'about.stats.countries': 'Países Atendidos',
    'about.stats.satisfaction': 'Satisfacción del Cliente',
    'about.stats.support': 'Soporte Dedicado',
    'about.founder.title': 'Fundador y Desarrollador Principal',
    'about.founder.story.title': 'La persona detras de IberiaTech',
    'about.founder.story.text': 'Llevo mas de 5 años construyendo sitios web. Creci en España y vivo en Charleston, asi que conozco los dos mercados de primera mano. Empece IberiaTech porque vi demasiados negocios pagando mucho por sitios que no les servian. Cuando trabajas con nosotros, trabajas conmigo directamente.',
    'about.founder.experience.us': '5+ años de experiencia en el mercado estadounidense',
    'about.founder.experience.spain': 'Hablante nativo de español y experto en cultura',
    'about.mission': 'Lo que hacemos',
    'about.mission.text': 'Construimos sitios web para negocios en Charleston y España. Sitios que traen clientes de verdad, no solo que se ven bonitos.',
    'about.expertise': 'Como trabajamos',
    'about.expertise.text': 'Nos dices lo que necesita tu negocio. Lo construimos, lo lanzamos, y nos aseguramos de que funcione. Sin tecnicismos.',
    'services.title': 'Lo que ofrecemos',
    'services.subtitle': 'Sitios web para negocios. Precios claros, sin sorpresas.',
    'services.title2': 'Lo que construimos',
    'services.subtitle2': 'Sitios web para negocios en Charleston, España y mas. Hechos para traerte clientes.',
    'services.subtitle3': 'Sitios y apps que traen clientes y se pagan solos.',
    'services.page.title': 'Nuestros servicios',
    'services.page.subtitle': 'Sitios web, SEO, sitios bilingues, analytics y soporte. Sabras exactamente que recibes y cuando.',
    'services.webdev.title': 'Desarrollo Web',
    'services.mobile.title': 'Diseño Mobile-First',
    'services.bilingual.title': 'Sitios Web Bilingües',
    'services.security.title': 'Seguridad y Autenticación',
    'services.performance.title': 'SEO y Rendimiento',
    'services.support.title': 'Soporte Continuo',
    'services.ai.title': 'Características con IA',
    'portfolio.title2': 'Acerca de Luis Lozoya',
    'portfolio.subtitle2': 'Fundador de IberiaTech Solutions',
    'portfolio.subtitle3': 'Ayudo a pequeñas y medianas empresas en Charleston y España a crecer en línea con sitios web modernos y bilingües',
    'portfolio.project.title': 'Proyecto Destacado: Cursor Rules Hub',
    'portfolio.coming.title': 'Mi Experiencia',
    'portfolio.cta.title': '¿Listo para Comenzar Tu Proyecto?',
    'portfolio.cta.start': 'Comenzar Tu Proyecto',
    'portfolio.cta.contact': 'Ponte en Contacto',
    'contact.title2': 'Cuentanos sobre tu proyecto',
    'contact.subtitle2': 'Envianos un mensaje. Te respondemos en 24 horas.',
    'contact.form.name': 'Tu nombre completo',
    'contact.form.company': 'Nombre de tu empresa',
    'contact.form.message': 'Cuéntame sobre tu proyecto...',
    'contact.form.sending': 'Enviando...',
    'pricing.title': 'Precios claros, sin sorpresas',
    'pricing.anchor': 'Sitios desde 1.000 €. Mira los rangos abajo para ver si encajamos en tu presupuesto.',
    'pricing.subtitle': 'Precio unico. Pagas, construimos, y es tuyo. Sin suscripciones, sin costos ocultos.',
    'pricing.subtitle.charleston': 'Precios justos para Charleston, SC y mas.',
    'pricing.value': 'Buen trabajo a precios honestos. Sabras exactamente por lo que pagas.',
    'pricing.starter.name': 'Básico',
    'pricing.starter.price': '1.000 – 1.800 €',
    'pricing.starter.desc': '',
    'pricing.business.name': 'Empresarial',
    'pricing.business.price': '2.000 – 4.000 €',
    'pricing.business.desc': '',
    'pricing.custom.name': 'Personalizado',
    'pricing.custom.price': 'Desde 4.000 €',
    'pricing.custom.desc': '',
    'pricing.popular': 'Más Popular',
    'pricing.getstarted': 'Comenzar',
    'pricing.cta.starter': 'Lanzar Mi Sitio Web',
    'pricing.cta.business': 'Hacer Crecer Mi Negocio',
    'pricing.cta.custom': 'Solicitar Cotización',
    'pricing.custom': '¿Listo para comenzar? Hablemos sobre tu proyecto →',
    'pricing.consultation': 'Todos los paquetes incluyen consulta gratuita y planificación de proyecto',
    'pricing.compare.title': 'Comparar planes',
    'pricing.compare.why': '¿Por qué este precio? Compara manzanas con manzanas.',
    'pricing.compare.whySub': 'Qué incluye cada nivel.',
    'pricing.compare.pages': 'Páginas',
    'pricing.compare.seo': 'SEO',
    'pricing.compare.analytics': 'Analytics',
    'pricing.compare.delivery': 'Entrega',
    'pricing.compare.revisions': 'Revisiones',
    'pricing.compare.support': 'Soporte post-lanzamiento',
    'pricing.compare.bilingual': 'Inglés + Español',
    'pricing.compare.starter.pages': 'Hasta 4 (ej. Inicio, Nosotros, Servicios, Contacto)',
    'pricing.compare.starter.seo': 'Básico (meta, mapa del sitio)',
    'pricing.compare.starter.analytics': 'No',
    'pricing.compare.starter.delivery': '1 semana',
    'pricing.compare.starter.revisions': '2 rondas',
    'pricing.compare.starter.support': '1 mes',
    'pricing.compare.starter.bilingual': 'Incluido',
    'pricing.compare.business.pages': 'Hasta 7 (ej. Inicio, Nosotros, Servicios, Portafolio, Testimonios, FAQ, Contacto)',
    'pricing.compare.business.seo': 'Avanzado + Google Analytics',
    'pricing.compare.business.analytics': 'Incluido',
    'pricing.compare.business.delivery': '2–4 semanas',
    'pricing.compare.business.revisions': '3 rondas',
    'pricing.compare.business.support': '3 meses',
    'pricing.compare.business.bilingual': 'Incluido (adaptación cultural)',
    'pricing.compare.custom': 'A medida',
    'pricing.compare.feature': 'Qué incluye',
    'pricing.compare.custom.pages': 'A medida (eCommerce, reservas, portales socios, formularios)',
    'pricing.compare.custom.seo': 'SEO + Analytics completo',
    'pricing.compare.custom.analytics': 'Incluido',
    'pricing.compare.custom.delivery': '5–7 semanas',
    'pricing.compare.custom.revisions': 'Incluido',
    'pricing.compare.custom.support': '6 meses',
    'pricing.compare.custom.bilingual': 'Incluido',
    'pricing.maintenance.title': 'Soporte mensual opcional',
    'pricing.maintenance.subtitle': 'Tranquilidad sin sorpresas. Planes recurrentes para actualizaciones, copias y mejoras.',
    'pricing.maintenance.basic.name': 'Soporte Básico',
    'pricing.maintenance.basic.price': '49 €/mes',
    'pricing.maintenance.basic.desc': 'Actualizaciones y copias de seguridad. Mantén tu sitio seguro y al día.',
    'pricing.maintenance.growth.name': 'Soporte Crecimiento',
    'pricing.maintenance.growth.price': '99 €/mes',
    'pricing.maintenance.growth.desc': 'Básico + revisión de analytics y ajustes SEO. Ideal para crecer en tráfico.',
    'pricing.maintenance.premium.name': 'Soporte Premium',
    'pricing.maintenance.premium.price': '199 €/mes',
    'pricing.maintenance.premium.desc': 'Mantenimiento completo y mejoras. Actualizaciones de contenido, soporte prioritario y optimización continua.',
    'pricing.addons.title': 'Complementos opcionales',
    'pricing.addons.subtitle': 'Añade a cualquier paquete. Precio único, sin sorpresas.',
    'pricing.addons.chatbot.name': 'Integración de chatbot',
    'pricing.addons.chatbot.price': '199 €',
    'pricing.addons.chatbot.desc': 'Chat con IA en tu sitio. Responde a visitantes 24/7.',
    'pricing.addons.seo.name': 'Paquete SEO avanzado',
    'pricing.addons.seo.price': '299 €',
    'pricing.addons.seo.desc': 'Optimización profunda, SEO local, datos estructurados.',
    'pricing.addons.analytics.name': 'Configuración Analytics premium',
    'pricing.addons.analytics.price': '249 €',
    'pricing.addons.analytics.desc': 'Google Analytics 4, objetivos y seguimiento de conversiones.',
    'pricing.payment.title': 'Opciones de pago',
    'pricing.payment.subtitle': 'Formas flexibles de pagar. Sin sorpresas.',
    'pricing.payment.option1': '50% al inicio, 50% al lanzamiento (todos los paquetes)',
    'pricing.payment.option2': 'Planes de pago en 2–3 etapas disponibles bajo petición',
    'services.detail.title': 'Qué incluye',
    'services.detail.seo.title': 'Entregables SEO',
    'services.detail.seo.desc': 'Lo que incluimos para que aparezcas en Google:',
    'services.detail.seo.1': 'Meta títulos y descripciones (cada página)',
    'services.detail.seo.2': 'Mapa del sitio + estructura móvil',
    'services.detail.seo.3': 'Schema básico (Empresarial+: datos estructurados)',
    'services.detail.seo.4': 'Carga rápida y URLs limpias',
    'services.detail.ai.title': 'Qué significa "con IA"',
    'services.detail.ai.desc': 'Usamos IA para que tu sitio trabaje más: chatbot opcional que responde a visitantes, formularios inteligentes y sugerencias de contenido. Sin costo extra en Empresarial y Premium.',
    'services.detail.timeline.title': 'Plazo de entrega',
    'services.detail.timeline.desc': 'Básico: 1 semana. Empresarial: 2–4 semanas. Premium / eCommerce: 5–7 semanas. Confirmamos fechas antes de empezar.',
    'services.detail.hosting.title': 'Dominio + hosting',
    'services.detail.hosting.desc': 'Te guiamos paso a paso (tú mantienes el control) o lo configuramos nosotros. El hosting no está incluido en el precio del proyecto; recomendamos opciones económicas.',
    'faq.title': 'Preguntas frecuentes',
    'faq.subtitle': 'Preguntas habituales antes de empezar.',
    'faq.q1': '¿Cuánto tarda el proyecto?',
    'faq.a1': 'Sitios Básico: 1 semana. Empresarial (5–7 páginas): 2–4 semanas. Premium / eCommerce: 5–7 semanas. Acordamos el plazo antes de empezar.',
    'faq.q2': '¿Qué soporte tengo después del lanzamiento?',
    'faq.a2': 'Básico incluye 1 mes de soporte; Empresarial 3 meses; Premium 6 meses. Después puedes contratar un plan mensual Care o Growth.',
    'faq.q3': '¿Cuántas revisiones incluye?',
    'faq.a3': 'Básico: 2 rondas. Empresarial: 3 rondas. Premium: revisiones incluidas según alcance. Lo confirmamos en tu cotización.',
    'faq.q4': '¿Gestionáis dominio y hosting?',
    'faq.a4': 'Podemos configurar dominio y hosting por ti o guiarte. El hosting no está incluido en el precio; recomendamos proveedores económicos y ayudamos con la configuración.',
    'faq.q5': '¿Tengo que comprar el dominio yo?',
    'faq.a5': 'Puedes comprar tu dominio (te decimos dónde y cómo) o nosotros lo compramos y lo conectamos. En cualquier caso, el dominio queda a tu nombre.',
    'faq.q6': '¿Y el mantenimiento continuo?',
    'faq.a6': 'Ofrecemos planes mensuales Care (actualizaciones, copias, supervisión) y Growth (Care + contenido y SEO). Ideales si quieres ayuda continua sin contratar a nadie.',
    'results.title': 'Resultados reales',
    'results.metric': 'Nuestros clientes ven hasta un 30% mas de leads en los primeros 90 dias.',
    'results.subtitle': 'Nos importa lo que pasa despues de que tu sitio esta online.',
    'guarantee.title': 'Tu tranquilidad',
    'guarantee.moneyback': 'Devolución si no estás satisfecho antes del lanzamiento',
    'guarantee.satisfaction': 'Garantía de satisfacción. Lo arreglamos hasta que estés contento.',
    'guarantee.timeline': 'Compromiso de plazo. Cumplimos las fechas acordadas.',
    'problems.title': '¿Te suena familiar?',
    'problems.subtitle': 'Muchos negocios en Charleston y España todavia dependen solo del boca a boca. Funciona hasta que deja de funcionar.',
    'problems.without.title': 'Sin un buen sitio web:',
    'problems.with.title': 'Con nosotros:',
    'problems.cta.title': '¿Listo para solucionarlo?',
    'problems.cta.subtitle': '',
    'problems.cta.button': 'Empezar hoy',
    'portfolio.title': 'Nuestro trabajo',
    'portfolio.subtitle': 'Sitios reales que hemos construido para negocios reales',
    'contact.title': 'Cuentanos sobre tu proyecto',
    'contact.subtitle': 'Dinos lo que necesitas. Te respondemos en 24 horas.',
    'contact.name': 'Nombre',
    'contact.email': 'Correo Electrónico',
    'contact.company': 'Empresa',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.phone': 'Teléfono',
    'contact.location': 'Ubicación',
    'footer.company': 'IberiaTech Solutions',
    'footer.description': 'Sitios web bilingues para negocios en Charleston y España.',
    'footer.services': 'Servicios',
    'footer.services.webdev': 'Desarrollo Web Personalizado',
    'footer.services.react': 'Diseño Web Moderno',
    'footer.services.supabase': 'Gestión Segura de Datos',
    'footer.services.bilingual': 'Sitios Web Bilingües',
    'footer.services.translation': 'Traducción de Sitios Web',
    'footer.services.seo': 'Optimización SEO',
    'footer.services.mobile': 'Diseño Mobile-Friendly',
    'visual.sites.title': 'Trabajo reciente',
    'visual.sites.subtitle': 'Sitios reales, negocios reales. Haz clic para verlos en vivo.',
    'portfolio.disclaimer': 'Nota: Los proyectos mostrados incluyen tanto clientes independientes de IberiaTech Solutions como trabajo profesional que Luis Lozoya completó como contratista para agencias socias.',
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    // Detect browser language
    const detectBrowserLanguage = (): Language => {
      if (typeof window === 'undefined') return 'en'
      
      // Check localStorage first for user preference
      const savedLanguage = localStorage.getItem('preferred-language') as Language
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'es')) {
        return savedLanguage
      }
      
      // Detect browser language
      const browserLang = navigator.language || navigator.languages?.[0] || 'en'
      
      // Check if browser language is Spanish
      if (browserLang.startsWith('es')) {
        return 'es'
      }
      
      // Default to English for all other languages
      return 'en'
    }

    const detectedLanguage = detectBrowserLanguage()
    setLanguage(detectedLanguage)
    setMounted(true)
  }, [])

  const handleLanguageChange = (newLanguage: Language) => {
    setLanguage(newLanguage)
    // Persist user's language choice
    if (typeof window !== 'undefined') {
      localStorage.setItem('preferred-language', newLanguage)
    }
  }

  const t = (key: string): string => {
    const val = translations[language][key as keyof typeof translations[typeof language]]
    return val !== undefined && val !== null ? val : key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleLanguageChange, t, mounted }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
