'use client'

import Link from 'next/link'
import { useLanguage } from '@/components/LanguageProvider'

/**
 * Legal notice and terms of use, in one page because the site is small enough
 * that splitting them would make two thin pages instead of one readable one.
 *
 * The part that matters most is the chat. It answers in the company's name, and
 * the model behind it can be wrong, so this page says plainly that nothing it
 * says is a quote or a commitment. The legal-notice block identifies who runs
 * the site, which a Spanish reader expects as the "aviso legal".
 *
 * Same rules as `/privacy`: bilingual inline, and every claim is a fact about
 * the site. If the site starts selling anything directly, this page changes in
 * the same commit.
 */
export default function TermsPage() {
  const { language } = useLanguage()
  const es = language === 'es'

  const sections: { title: string; body: React.ReactNode }[] = es
    ? [
        {
          title: 'Quién está detrás',
          body: (
            <p>
              Esta web la gestiona IberiaTech Solutions LLC, sociedad de
              responsabilidad limitada registrada en Carolina del Sur (Estados
              Unidos), con domicilio en Charleston. Contacto:{' '}
              <strong>luis@iberiatechsolutions.com</strong>.
            </p>
          ),
        },
        {
          title: 'Para qué es esta web',
          body: (
            <p>
              Para contar qué hacemos y cómo contactarnos. Nada de lo que hay
              aquí es una oferta vinculante. Cada proyecto se presupuesta y se
              acuerda por escrito, y es ese acuerdo el que cuenta.
            </p>
          ),
        },
        {
          title: 'El chat',
          body: (
            <p>
              Las respuestas del chat las genera un programa, a veces con un
              modelo de IA, y pueden contener errores. No son un presupuesto, ni
              un compromiso, ni asesoramiento profesional. Si algo importa para
              una decisión, confírmalo por correo con una persona.
            </p>
          ),
        },
        {
          title: 'Contenido',
          body: (
            <p>
              Los textos, el diseño y el código de esta web son de IberiaTech
              Solutions LLC. Los nombres y marcas de los proyectos que aparecen
              en el portfolio pertenecen a sus dueños y se muestran como
              ejemplos de trabajo realizado.
            </p>
          ),
        },
        {
          title: 'Enlaces a otras webs',
          body: (
            <p>
              La web enlaza a otros sitios (Calendly, WhatsApp, LinkedIn y los
              proyectos del portfolio). Lo que pase en ellos depende de sus
              propios dueños y condiciones.
            </p>
          ),
        },
        {
          title: 'Responsabilidad',
          body: (
            <p>
              La web se ofrece tal cual. Intentamos que la información sea
              correcta y esté al día, pero no podemos garantizarlo. En la medida
              en que la ley lo permite, no respondemos de daños derivados de
              usarla. Nada de esto limita los derechos que la ley te reconoce
              como consumidor.
            </p>
          ),
        },
        {
          title: 'Ley aplicable',
          body: (
            <p>
              Estas condiciones se rigen por las leyes de Carolina del Sur
              (Estados Unidos). Si eres consumidor en la UE, conservas además la
              protección que te dan las leyes de tu país.
            </p>
          ),
        },
      ]
    : [
        {
          title: 'Who runs this site',
          body: (
            <p>
              This site is run by IberiaTech Solutions LLC, a limited liability
              company registered in South Carolina, United States, and based in
              Charleston. Contact:{' '}
              <strong>luis@iberiatechsolutions.com</strong>.
            </p>
          ),
        },
        {
          title: 'What this site is for',
          body: (
            <p>
              Describing what we do and how to get in touch. Nothing here is a
              binding offer. Every project is quoted and agreed in writing, and
              that agreement is what counts.
            </p>
          ),
        },
        {
          title: 'The chat',
          body: (
            <p>
              Chat replies are generated by software, sometimes by an AI model,
              and can be wrong. They are not a quote, a commitment, or
              professional advice. If something matters for a decision, confirm
              it by email with a person.
            </p>
          ),
        },
        {
          title: 'Content',
          body: (
            <p>
              The text, design and code of this site belong to IberiaTech
              Solutions LLC. Project names and marks shown in the portfolio
              belong to their owners and appear as examples of work done.
            </p>
          ),
        },
        {
          title: 'Links to other sites',
          body: (
            <p>
              This site links to others (Calendly, WhatsApp, LinkedIn, and the
              portfolio projects). What happens there is up to their owners and
              their own terms.
            </p>
          ),
        },
        {
          title: 'Liability',
          body: (
            <p>
              The site is provided as is. We try to keep the information
              accurate and current but cannot guarantee it. To the extent the
              law allows, we are not liable for damages arising from its use.
              Nothing here limits rights the law gives you as a consumer.
            </p>
          ),
        },
        {
          title: 'Governing law',
          body: (
            <p>
              These terms are governed by the laws of South Carolina, United
              States. If you are a consumer in the EU, you also keep the
              protection your own country&apos;s laws give you.
            </p>
          ),
        },
      ]

  return (
    <div className="min-h-screen section-padding">
      <div className="container-max">
        <div className="max-w-2xl">
          <p className="text-xs uppercase tracking-[0.25em] text-accent-700 dark:text-accent-400 font-medium mb-5">
            {es ? 'Aviso legal' : 'Legal notice'}
          </p>
          <h1 className="font-display text-4xl md:text-6xl font-semibold text-ink-900 dark:text-ink-50 leading-[1.05] mb-8">
            {es ? 'Condiciones de uso' : 'Terms of use'}
          </h1>
          <p className="font-display text-xl md:text-2xl text-ink-700 dark:text-ink-300 leading-snug mb-16 prose-measure">
            {es
              ? 'Quién está detrás de esta web y qué puedes esperar de ella. Lo que se recoge al visitarla está en '
              : 'Who is behind this site and what you can expect from it. What it collects is on the '}
            <Link href="/privacy" className="underline underline-offset-4 hover:text-ink-900 dark:hover:text-ink-100">
              {es ? 'página de privacidad' : 'privacy page'}
            </Link>
            .
          </p>

          <div className="space-y-12">
            {sections.map((s) => (
              <section key={s.title}>
                <h2 className="font-display text-xl font-semibold text-ink-900 dark:text-ink-50 mb-3">
                  {s.title}
                </h2>
                <div className="space-y-3 text-ink-700 dark:text-ink-300 leading-relaxed prose-measure">
                  {s.body}
                </div>
              </section>
            ))}
          </div>

          <p className="mt-16 pt-8 border-t border-ink-200 dark:border-ink-800 text-sm text-ink-500">
            {es ? 'Actualizado el 3 de octubre de 2026.' : 'Last updated 3 October 2026.'}{' '}
            <Link href="/contact" className="underline underline-offset-4 hover:text-ink-900 dark:hover:text-ink-100">
              {es ? 'Contacto' : 'Contact'}
            </Link>
          </p>
        </div>
      </div>
    </div>
  )
}
